### ISSUE TITLE
Install dependencies

### ISSUE THREAD

**Issue by dhruvparamhans** [sourcegraph/thyme#36]
I have a working go installation. However when I run thyme dep, it gives the following message:
   
    Install the following command-line utilities via your package manager (e.g., apt) of choice:
    * xdpyinfo
    * xwininfo
    * xdotool
    * wmctrl

However all these utilities are already installed. I am not a go programmer so maybe I am missing something.

**Comment by HalfVoxel** [comment]
Thyme dep simply lists dependencies, it's not an error.
See also #29

**Comment by zyphlar** [comment]
`apt-get install xdpyinfo xwininfo xdotool wmctrl` fails with

```
E: Unable to locate package xdpyinfo
E: Unable to locate package xwininfo
```

However it turns out (after googling, and then installing apt-file to discover which package provides these programs) that those programs were already installed (via x11-utils).

**Suggested fix:** check for which dependencies are actually installed already and indicate which ones need to be installed. Perhaps also mention the deb/rpm/etc package names to save users ~10 mins.

I think between this and the issue I posted the other day I've spent 30 mins trying to get a time tracking program working, which is kinda funny :P

**Comment by beyang** [comment]
Yep, absolutely agree, thanks for pointing this out. I'll unfortunately have limited time to work on this in the next couple of weeks, but I think this should be an easy fix. Thyme just needs to detect if the commands are installed (via [LookPath()](https://sourcegraph.com/github.com/golang/go/-/info/GoPackage/os/exec/-/LookPath)) before printing out the instructions. The only function you need to modify is [LinuxTracker.Deps](https://sourcegraph.com/github.com/sourcegraph/thyme@4ab2582994d38652622d2aaa3dbf30b665b2b228/-/def/GoPackage/github.com/sourcegraph/thyme/-/LinuxTracker/Deps).

**Comment by beyang** [comment]
After seeing some of the other issues folks have reported, I'm a little hesitant to auto-install dependencies. I'd like to wait for things to stabilize a bit. For now, I'd prefer to keep manual installation instructions, as they're more flexible and less prone to break as the dependencies might change. See the last comment here: https://github.com/sourcegraph/thyme/pull/48.

If anyone has strong disagreements, feel free to re-open and comment.
